"""
Configuration file for RMP Ashmore Data Mapper
Contains RMP column headers and mappings
"""

# RMP Column Order (Row 1) - Technical column names
RMP_COLUMN_ORDER = [
    "",
    "RMP.ASHMORE.CURRENCYEXPOSURE.MYR.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.IDR.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.MXN.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.THB.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.ZAR.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.PLN.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.INR.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.CNY.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.BRL.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.TRY.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.CZK.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.HUF.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.TOTAL.FUND.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.MYR.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.IDR.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.MXN.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.THB.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.ZAR.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.PLN.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.INR.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.CNY.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.BRL.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.TRY.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.TOTAL.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.CZK.BENCHMARK.M",
    "RMP.ASHMORE.CURRENCYEXPOSURE.HUF.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.MYS.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.CHN.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.IDN.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.MEX.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.THA.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.ZAF.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.POL.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.BRA.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.TUR.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.CZE.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.TOTAL.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.MYS.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.CHN.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.IDN.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.MEX.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.THA.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.ZAF.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.POL.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.BRA.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.TUR.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.CZE.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.TOTAL.BENCHMARK.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.IND.FUND.M",
    "RMP.ASHMORE.COUNTRYEXPOSURE.IND.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.YIELDTOMATURITY.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.AVERAGECOUPON.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.CURRENTYIELD.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.MODIFIEDDURATION.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.AVERAGELIFE.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.DISTRIBUTIONYIELD.FUND.M",
    "RMP.ASHMORE.FUNDSTATISTICS.YIELDTOMATURITY.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.AVERAGECOUPON.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.CURRENTYIELD.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.MODIFIEDDURATION.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.AVERAGELIFE.BENCHMARK.M",
    "RMP.ASHMORE.FUNDSTATISTICS.DISTRIBUTIONYIELD.BENCHMARK.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.BRL.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.BRL.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.BRL.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.BRL.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.NGN.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.NGN.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.NGN.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.NGN.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.TRY.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.TRY.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.TRY.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.TRY.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.COP.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.COP.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.COP.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.COP.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CLP.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CLP.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CLP.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CLP.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PEN.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PEN.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PEN.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PEN.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PLN.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PLN.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PLN.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.PLN.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CZK.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CZK.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CZK.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CZK.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.EGP.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.EGP.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.EGP.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.EGP.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MXN.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MXN.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MXN.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MXN.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ZAR.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ZAR.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ZAR.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ZAR.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.KRW.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.KRW.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.KRW.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.KRW.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MYR.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MYR.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MYR.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.MYR.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.INR.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.INR.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.INR.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.INR.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.THB.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.THB.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.THB.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.THB.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNH.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNH.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNH.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNH.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNY.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNY.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNY.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.CNY.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ARS.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ARS.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ARS.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.ARS.TOTAL.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.HUF.ASSETALLOCATION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.HUF.SECURITYSELECTION.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.HUF.CURRENCYEFFECT.M",
    "RMP.ASHMORE.PERFORMANCEATTRIBUTION.HUF.TOTAL.M"
]

# RMP Header Row 2 - Descriptive labels (quoted for CSV)
RMP_HEADER_ROW2 = [
    "",
    '"Currency exposure, Malaysian Ringgit, Fund"',
    '"Currency exposure, Indonesian Rupiah, Fund"',
    '"Currency exposure, Mexican Peso, Fund"',
    '"Currency exposure, Thai Baht, Fund"',
    '"Currency exposure, South African Rand, Fund"',
    '"Currency exposure, Polish Zloty, Fund"',
    '"Currency exposure, Indian Rupee, Fund"',
    '"Currency exposure, Chinese Yuan (onshore), Fund"',
    '"Currency exposure, Brazilian Real, Fund"',
    '"Currency exposure, Turkish Lira, Fund"',
    '"Currency exposure, Czech Koruna, Fund"',
    '"Currency exposure, Hungarian Forint, Fund"',
    '"Currency exposure, Total number of currencies, Fund"',
    '"Currency exposure, Malaysian Ringgit, Benchmark"',
    '"Currency exposure, Indonesian Rupiah, Benchmark"',
    '"Currency exposure, Mexican Peso, Benchmark"',
    '"Currency exposure, Thai Baht, Benchmark"',
    '"Currency exposure, South African Rand, Benchmark"',
    '"Currency exposure, Polish Zloty, Benchmark"',
    '"Currency exposure, Indian Rupee, Benchmark"',
    '"Currency exposure, Chinese Yuan (onshore), Benchmark"',
    '"Currency exposure, Brazilian Real, Benchmark"',
    '"Currency exposure, Turkish Lira, Benchmark"',
    '"Currency exposure, Total number of currencies, Benchmark"',
    '"Currency exposure, Czech Koruna, Benchmark"',
    '"Currency exposure, Hungarian Forint, Benchmark"',
    '"Country exposure, Malaysia, Fund"',
    '"Country exposure, China, Fund"',
    '"Country exposure, Indonesia, Fund"',
    '"Country exposure, Mexico, Fund"',
    '"Country exposure, Thailand, Fund"',
    '"Country exposure, South Africa, Fund"',
    '"Country exposure, Poland, Fund"',
    '"Country exposure, Brazil, Fund"',
    '"Country exposure, Turkiye, Fund"',
    '"Country exposure, Czech Republic, Fund"',
    '"Country exposure, Total number of countries, Fund"',
    '"Country exposure, Malaysia, Benchmark"',
    '"Country exposure, China, Benchmark"',
    '"Country exposure, Indonesia, Benchmark"',
    '"Country exposure, Mexico, Benchmark"',
    '"Country exposure, Thailand, Benchmark"',
    '"Country exposure, South Africa, Benchmark"',
    '"Country exposure, Poland, Benchmark"',
    '"Country exposure, Brazil, Benchmark"',
    '"Country exposure, Turkiye, Benchmark"',
    '"Country exposure, Czech Republic, Benchmark"',
    '"Country exposure, Total number of countries, Benchmark"',
    '"Country exposure, India, Fund"',
    '"Country exposure, india, Benchmark"',
    '"Fund statistics, Yield to maturity, Fund"',
    '"Fund statistics, Average coupon, Fund"',
    '"Fund statistics, Current yield, Fund"',
    '"Fund statistics, Modified duration, Fund"',
    '"Fund statistics, Average life, Fund"',
    '"Fund statistics, Distribution yield, Fund"',
    '"Fund statistics, Yield to maturity, Benchmark"',
    '"Fund statistics, Average coupon, Benchmark"',
    '"Fund statistics, Current yield, Benchmark"',
    '"Fund statistics, Modified duration, Benchmark"',
    '"Fund statistics, Average life, Benchmark"',
    '"Fund statistics, Distribution yield, Benchmark"',
    '"Performance attribution, Brazilian Real, Asset Allocation"',
    '"Performance attribution, Brazilian Real, Security Selection"',
    '"Performance attribution, Brazilian Real, Currency Effect"',
    '"Performance attribution, Brazilian Real, Total"',
    '"Performance attribution, Nigerian Naira, Asset Allocation"',
    '"Performance attribution, Nigerian Naira, Security Selection"',
    '"Performance attribution, Nigerian Naira, Currency Effect"',
    '"Performance attribution, Nigerian Naira, Total"',
    '"Performance attribution, Turkish Lira, Asset Allocation"',
    '"Performance attribution, Turkish Lira, Security Selection"',
    '"Performance attribution, Turkish Lira, Currency Effect"',
    '"Performance attribution, Turkish Lira, Total"',
    '"Performance attribution, Colombian Peso, Asset Allocation"',
    '"Performance attribution, Colombian Peso, Security Selection"',
    '"Performance attribution, Colombian Peso, Currency Effect"',
    '"Performance attribution, Colombian Peso, Total"',
    '"Performance attribution, Chilean Peso, Asset Allocation"',
    '"Performance attribution, Chilean Peso, Security Selection"',
    '"Performance attribution, Chilean Peso, Currency Effect"',
    '"Performance attribution, Chilean Peso, Total"',
    '"Performance attribution, Peruvian Sol, Asset Allocation"',
    '"Performance attribution, Peruvian Sol, Security Selection"',
    '"Performance attribution, Peruvian Sol, Currency Effect"',
    '"Performance attribution, Peruvian Sol, Total"',
    '"Performance attribution, Polish Zloty, Asset Allocation"',
    '"Performance attribution, Polish Zloty, Security Selection"',
    '"Performance attribution, Polish Zloty, Currency Effect"',
    '"Performance attribution, Polish Zloty, Total"',
    '"Performance attribution, Czech Koruna, Asset Allocation"',
    '"Performance attribution, Czech Koruna, Security Selection"',
    '"Performance attribution, Czech Koruna, Currency Effect"',
    '"Performance attribution, Czech Koruna, Total"',
    '"Performance attribution, Egyptian Pound, Asset Allocation"',
    '"Performance attribution, Egyptian Pound, Security Selection"',
    '"Performance attribution, Egyptian Pound, Currency Effect"',
    '"Performance attribution, Egyptian Pound, Total"',
    '"Performance attribution, Mexican Peso, Asset Allocation"',
    '"Performance attribution, Mexican Peso, Security Selection"',
    '"Performance attribution, Mexican Peso, Currency Effect"',
    '"Performance attribution, Mexican Peso, Total"',
    '"Performance attribution, South African Rand, Asset Allocation"',
    '"Performance attribution, South African Rand, Security Selection"',
    '"Performance attribution, South African Rand, Currency Effect"',
    '"Performance attribution, South African Rand, Total"',
    '"Performance attribution, South Korean Won, Asset Allocation"',
    '"Performance attribution, South Korean Won, Security Selection"',
    '"Performance attribution, South Korean Won, Currency Effect"',
    '"Performance attribution, South Korean Won, Total"',
    '"Performance attribution, Malaysian Ringgit, Asset Allocation"',
    '"Performance attribution, Malaysian Ringgit, Security Selection"',
    '"Performance attribution, Malaysian Ringgit, Currency Effect"',
    '"Performance attribution, Malaysian Ringgit, Total"',
    '"Performance attribution, Indian Rupee, Asset Allocation"',
    '"Performance attribution, Indian Rupee, Security Selection"',
    '"Performance attribution, Indian Rupee, Currency Effect"',
    '"Performance attribution, Indian Rupee, Total"',
    '"Performance attribution, Thai Baht, Asset Allocation"',
    '"Performance attribution, Thai Baht, Security Selection"',
    '"Performance attribution, Thai Baht, Currency Effect"',
    '"Performance attribution, Thai Baht, Total"',
    '"Performance attribution, Chinese Yuan (offshore), Asset Allocation"',
    '"Performance attribution, Chinese Yuan (offshore), Security Selection"',
    '"Performance attribution, Chinese Yuan (offshore), Currency Effect"',
    '"Performance attribution, Chinese Yuan (offshore), Total"',
    '"Performance attribution, Chinese Yuan (onshore), Asset Allocation"',
    '"Performance attribution, Chinese Yuan (onshore), Security Selection"',
    '"Performance attribution, Chinese Yuan (onshore), Currency Effect"',
    '"Performance attribution, Chinese Yuan (onshore), Total"',
    '"Performance attribution, Argentine Peso, Asset Allocation"',
    '"Performance attribution, Argentine Peso, Security Selection"',
    '"Performance attribution, Argentine Peso, Currency Effect"',
    '"Performance attribution, Argentine Peso, Total"',
    '"Performance attribution, Hungarian Forint, Asset Allocation"',
    '"Performance attribution, Hungarian Forint, Security Selection"',
    '"Performance attribution, Hungarian Forint, Currency Effect"',
    '"Performance attribution, Hungarian Forint, Total"'
]

# Currency name to ISO code mapping
CURRENCY_CODE_MAP = {
    "Mexican Peso": "MXN",
    "Malaysian Ringgit": "MYR",
    "Indian Rupee": "INR",
    "Indonesian Rupiah": "IDR",
    "Polish Zloty": "PLN",
    "Thai Baht": "THB",
    "Brazilian Real": "BRL",
    "South African Rand": "ZAR",
    "Czech Koruna": "CZK",
    "Hungarian Forint": "HUF",
    "Chinese Yuan (offshore)": "CNH",
    "Chinese Yuan (onshore)": "CNY",
    "Nigerian Naira": "NGN",
    "Argentine Peso": "ARS",
    "South Korean Won": "KRW",
    "Turkish Lira": "TRY",
    "Colombian Peso": "COP",
    "Chilean Peso": "CLP",
    "Peruvian Sol": "PEN",
    "Egyptian Pound": "EGP"
}

# Country name to ISO code mapping
COUNTRY_CODE_MAP = {
    "Mexico": "MEX",
    "Malaysia": "MYS",
    "India": "IND",
    "Indonesia": "IDN",
    "Poland": "POL",
    "Thailand": "THA",
    "Brazil": "BRA",
    "South Africa": "ZAF",
    "Czech Republic": "CZE",
    "Hungary": "HUN",
    "China": "CHN",
    "Turkey": "TUR",
    "Turkiye": "TUR"
}

# Fund statistics name mapping
FUND_STATS_MAP = {
    "Yield to maturity": "YIELDTOMATURITY",
    "Average coupon": "AVERAGECOUPON",
    "Current yield": "CURRENTYIELD",
    "Modified duration": "MODIFIEDDURATION",
    "Average life": "AVERAGELIFE",
    "Distribution yield": "DISTRIBUTIONYIELD"
}
